### ISSUE TITLE
Generate data rag to rag + tools

### ISSUE THREAD

**Issue by ankush13r** [langtech-bsc/Function-Calling#2]

**Comment by ankush13r** [comment]
https://huggingface.co/datasets/BSC-LT/RAG_Multilingual_Conversational_Fastchat

**Comment by cbarone511** [comment]
ChatUI funciona pero después de hablar dos veces el modelo se olvida y a la tercera vez que se le habla no tiene contexto, se borra el historial -> modificarlo
Habría que generar un nuevo dataset para Q/A o modificar el ChatUI para que el modelo conserve el contexto.

**Comment by ankush13r** [comment]
As I mentioned before, chat-ui now works with function calling, and the vllm API also supports tools. So, we have a good portion of the work already done.

What’s left:

I’ve done fine-tuning on the model trained by Jaume, but it seems to be overfitting, as it starts using tools all the time, even when you don’t ask for them (catastrophic forgetting). I’ve found that there are several methods for this type of fine-tuning:

1. **Elastic Weight Consolidation (EWC)**: This method penalizes important parameters to prevent the model from forgetting previous information.
2. **Partial Data Training**: This involves including a portion of the original training data to avoid overfitting.
3. **Base Model Training**: Retraining the base model with all data.

At the moment, I’m leaning toward the third option, so we’ll see how it performs. Any feedback from you would be very helpful.

**Comment by ankush13r** [comment]
Hay otras tareas abierta relacionadas con function calling y RAG:
- #1
- #4 
Cierro está tarea por eso.
